[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true
port = 54323

[api]
enabled = true
port = 54321

[auth]
enabled = true
site_url = "http://localhost:3001"

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:3001/auth/callback"
