import * as cdk from "aws-cdk-lib";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import * as ssm from "aws-cdk-lib/aws-ssm";
import type { Construct } from "constructs";
import type { InfraConfig } from "../config";
import { secretNames, ssmPaths } from "../naming";

export type AuthStackProps = cdk.StackProps & {
  config: InfraConfig;
};

/**
 * Auth stack: Secrets Manager resources for the admin app's Better Auth +
 * Google OAuth configuration. Values are injected out-of-band (Google) or
 * auto-generated (Better Auth signing secret). ARNs are published to the SSM
 * registry for the AdminStack to discover.
 */
export class AuthStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: AuthStackProps) {
    super(scope, id, props);
    const { config } = props;
    const names = secretNames(config);
    const paths = ssmPaths(config);

    const googleOAuthSecret = new secretsmanager.Secret(this, "GoogleOAuthSecret", {
      secretName: names.googleOAuth,
      description:
        "Google OAuth client id/secret JSON (value set out-of-band via put-secret-value)",
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const betterAuthSecret = new secretsmanager.Secret(this, "BetterAuthSecret", {
      secretName: names.betterAuthSecret,
      description: "Better Auth session signing secret (auto-generated by CDK)",
      generateSecretString: {
        passwordLength: 64,
        excludePunctuation: true,
      },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    new ssm.StringParameter(this, "GoogleOAuthArnParam", {
      parameterName: paths.googleOAuthArn,
      stringValue: googleOAuthSecret.secretArn,
    });
    new ssm.StringParameter(this, "BetterAuthSecretArnParam", {
      parameterName: paths.betterAuthSecretArn,
      stringValue: betterAuthSecret.secretArn,
    });

    new cdk.CfnOutput(this, "GoogleOAuthSecretArn", {
      value: googleOAuthSecret.secretArn,
    });
    new cdk.CfnOutput(this, "BetterAuthSecretArn", {
      value: betterAuthSecret.secretArn,
    });
  }
}
