export type {
  Hero,
  HeroFormData,
  About,
  AboutFormData,
  Experience,
  ExperienceFormData,
  Project,
  ProjectFormData,
  ProjectType,
  Skill,
  SkillFormData,
  SkillCategory,
  Resume,
  ResumeFormData,
  ResumeVariant,
  ResumeVariantFormData,
  Education,
  Certification,
  Testimonial,
  TestimonialFormData,
  BlogPost,
  SiteConfig,
  SiteConfigFormData,
  SocialLink,
  NavLink,
  Media,
  MediaInsert,
  ResumeGeneration,
  ResumeGenerationUsage,
  ResumeGenerationInsert,
  ResumeGenerationUpdate,
} from "../schemas";

export type Result<T> = { success: true; data: T } | { success: false; error: string };
