import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

/**
 * Validated environment for the web app. All vars are optional because the app
 * degrades gracefully (analytics no-op, chat returns 503, fixtures back the
 * data layer locally); marking required vars is deferred until CI provides them
 * and sets SKIP_ENV_VALIDATION for build-only steps.
 *
 * Imported from next.config.ts so validation runs at build/start.
 */
export const env = createEnv({
  server: {
    RESEND_API_KEY_SECRET_ARN: z.string().min(1).optional(),
    RESEND_API_KEY: z.string().min(1).optional(),
    CONTACT_TO_EMAIL: z.string().email().optional(),
    CONTACT_FROM_EMAIL: z.string().min(1).optional(),
    TURNSTILE_SECRET_KEY_SECRET_ARN: z.string().min(1).optional(),
    TURNSTILE_SECRET_KEY: z.string().min(1).optional(),
    GROQ_API_KEY_SECRET_ARN: z.string().min(1).optional(),
    CHAT_RATE_LIMIT_MAX: z.string().optional(),
    CHAT_RATE_LIMIT_WINDOW_SEC: z.string().optional(),
    CHAT_RESPONSE_CACHE_ENABLED: z.string().optional(),
    CHAT_RESPONSE_CACHE_TTL_SEC: z.string().optional(),
    CHAT_RESPONSE_CACHE_MAX_CHARS: z.string().optional(),
    GITHUB_TOKEN: z.string().min(1).optional(),
    POSTHOG_API_KEY: z.string().min(1).optional(),
    POSTHOG_PROJECT_ID: z.string().min(1).optional(),
    POSTHOG_APP_HOST: z.string().url().optional(),
    POSTHOG_ENVIRONMENT: z.string().optional(),
    DATA_BACKEND: z.enum(["fixture", "dynamo"]).optional(),
    DYNAMO_TABLE_PREFIX: z.string().min(1).optional(),
    DYNAMODB_LOCAL_ENDPOINT: z.string().url().optional(),
    AWS_REGION: z.string().min(1).optional(),
    S3_ENDPOINT: z.string().url().optional(),
    S3_MEDIA_BUCKET: z.string().min(1).optional(),
    MEDIA_PUBLIC_BASE_URL: z.string().url().optional(),
    OPEN_NEXT_BUILD_ID: z.string().min(1).optional(),
    GOOGLE_SITE_VERIFICATION: z.string().min(1).optional(),
    BING_SITE_VERIFICATION: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_SITE_URL: z.string().url().optional(),
    NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN: z.string().min(1).optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().url().optional(),
    NEXT_PUBLIC_POSTHOG_UI_HOST: z.string().url().optional(),
    NEXT_PUBLIC_POSTHOG_ENVIRONMENT: z.string().optional(),
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: z.string().min(1).optional(),
  },
  runtimeEnv: {
    RESEND_API_KEY_SECRET_ARN: process.env.RESEND_API_KEY_SECRET_ARN,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    CONTACT_TO_EMAIL: process.env.CONTACT_TO_EMAIL,
    CONTACT_FROM_EMAIL: process.env.CONTACT_FROM_EMAIL,
    TURNSTILE_SECRET_KEY_SECRET_ARN: process.env.TURNSTILE_SECRET_KEY_SECRET_ARN,
    TURNSTILE_SECRET_KEY: process.env.TURNSTILE_SECRET_KEY,
    GROQ_API_KEY_SECRET_ARN: process.env.GROQ_API_KEY_SECRET_ARN,
    CHAT_RATE_LIMIT_MAX: process.env.CHAT_RATE_LIMIT_MAX,
    CHAT_RATE_LIMIT_WINDOW_SEC: process.env.CHAT_RATE_LIMIT_WINDOW_SEC,
    CHAT_RESPONSE_CACHE_ENABLED: process.env.CHAT_RESPONSE_CACHE_ENABLED,
    CHAT_RESPONSE_CACHE_TTL_SEC: process.env.CHAT_RESPONSE_CACHE_TTL_SEC,
    CHAT_RESPONSE_CACHE_MAX_CHARS: process.env.CHAT_RESPONSE_CACHE_MAX_CHARS,
    GITHUB_TOKEN: process.env.GITHUB_TOKEN,
    POSTHOG_API_KEY: process.env.POSTHOG_API_KEY,
    POSTHOG_PROJECT_ID: process.env.POSTHOG_PROJECT_ID,
    POSTHOG_APP_HOST: process.env.POSTHOG_APP_HOST,
    POSTHOG_ENVIRONMENT: process.env.POSTHOG_ENVIRONMENT,
    DATA_BACKEND: process.env.DATA_BACKEND,
    DYNAMO_TABLE_PREFIX: process.env.DYNAMO_TABLE_PREFIX,
    DYNAMODB_LOCAL_ENDPOINT: process.env.DYNAMODB_LOCAL_ENDPOINT,
    AWS_REGION: process.env.AWS_REGION,
    S3_ENDPOINT: process.env.S3_ENDPOINT,
    S3_MEDIA_BUCKET: process.env.S3_MEDIA_BUCKET,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN: process.env.NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    NEXT_PUBLIC_POSTHOG_UI_HOST: process.env.NEXT_PUBLIC_POSTHOG_UI_HOST,
    NEXT_PUBLIC_POSTHOG_ENVIRONMENT: process.env.NEXT_PUBLIC_POSTHOG_ENVIRONMENT,
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
    MEDIA_PUBLIC_BASE_URL: process.env.MEDIA_PUBLIC_BASE_URL,
    OPEN_NEXT_BUILD_ID: process.env.OPEN_NEXT_BUILD_ID,
    GOOGLE_SITE_VERIFICATION: process.env.GOOGLE_SITE_VERIFICATION,
    BING_SITE_VERIFICATION: process.env.BING_SITE_VERIFICATION,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
